tasks:
  - command: |
      git config --global user.name $GITHUB_PUBLIC_NAME
      git config --global user.email $GITHUB_PUBLIC_EMAIL

vscode:
  extensions:
    - samuelcolvin.jinjahtml@0.16.0:BVmmMq9AdPxbGoooHnjjUg==