
tasks:
  - command: |
      git config --global user.name $GITHUB_PUBLIC_NAME
      git config --global user.email $GITHUB_PUBLIC_EMAIL

vscode:
  extensions:
    - vscoss.vscode-ansible@0.5.2:m6JJstDsTNOF8KJcya19UA==
    - samuelcolvin.jinjahtml@0.16.0:BVmmMq9AdPxbGoooHnjjUg==
    - wholroyd.jinja@0.0.8:C3zsj1nZxSJZh/EcV6Hjlg==git