---

# - name: start harbor
#   docker_compose:
#     project_src: "{{ harbor_install_dir }}/harbor"
#     files: "{{ harbor_docker_compose_files }}"
#     state: present
#     timeout: 30
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: collect facts about system services
  service_facts:

- name: Debug
  debug:
    var: ansible_facts.services['harbor.service']

- name: ensure harbor is started and enabled
  become: true
  service:
    name: harbor
    state: started
    enabled: true

- name: wait 15 seconds for clean startup
  pause:
    seconds: 15

- name: wait for health
  uri:
    url: "http://127.0.0.1:{{ harbor_exposed_http_port }}/api/version"
    method: GET
    user: "admin"
    password: "{{ harbor_admin_password | default('Harbor12345') }}"
    status_code:
      - 200
    headers:
      Content-Type: application/json
    body_format: json
    force_basic_auth: true
    return_content: true
  register: _harbor_version
  until: _harbor_version is succeeded
  ignore_errors: false
  retries: 10
  delay: 10

- debug:
    msg: "{{ harbor_version }}"
