---

# - name: stop harbor
#   docker_compose:
#     debug: true
#     project_src: "{{ harbor_install_dir }}/harbor"
#     files: "{{ harbor_docker_compose_files }}"
#     state: absent
#     timeout: 30
#   environment:
#     PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: collect facts about system services
  service_facts:

- name: Debug
  debug:
    var: ansible_facts.services['harbor.service']

- name: ensure harbor is stopped
  become: true
  service:
    name: harbor
    state: stopped
