---
- name: run installer
  become: true
  command: |
    /bin/bash ./install.sh {{ harbor_installer_with | default([]) | join(' ') }}
  args:
    chdir: "{{ harbor_install_dir }}/harbor"
    creates: '{{ harbor_install_dir }}/harbor/harbor_install_log.txt'
  environment:
    SHELL: /bin/bash
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    TERM: xterm

- name: reload service
  service:
    name: harbor
    state: reloaded
