---
- name: start harbor
  service:
    name: harbor
    state: started


- name: stop harbor
  service:
    name: harbor
    state: stopped

- name: run installer
  become: true
  command: |
    /bin/bash ./install.sh {{ harbor_installer_with | default([]) | join(' ') }} {{ harbor_installer_extra_args }}
  args:
    chdir: "{{ harbor_install_dir }}/harbor"
    creates: '{{ harbor_install_dir }}/harbor/harbor_install_log.txt'
  environment:
    SHELL: /bin/bash
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    TERM: xterm
  when:
    - not harbor_folder_st.stat.exists or (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)
