---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  vars:

    harbor_hostname: harbor
    harbor_installer_with:
      - --with-clair
      - --with-chartmuseum

    ansible_python_interpreter: python3

  roles:
    - role: ansible-role-harbor
